config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get 'search' => 'searches#search'

  resources :users, only: [:create, :show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower


  def follow(user_id)
    relationships.create(follow_id: user_id)
  end

  # ユーザーのフォローを外す、後ほどcontrollerで使用します。
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す、後ほどviewで使用します。
  def following?(user)
    followings.include?(user)
  end

  def self.search(search, word)
    if search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @user = User.where("#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end


  attachment :profile_image, destroy: false

  validates :name, presence: true, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# 投稿した本人だけが、投稿した本文の編集や削除ができるという制限をかけるには3つの操作が必要である。
# 1. ユーザがログイン済みかどうか。before_action :authenticate_user!
# 2. ログインしたユーザが投稿した本人かどうかview内で表示を分ける。
# 3. ログインしたユーザが投稿した本人かどうかをcontrollerで分ける def ensure_correct_user ~  unless @user == current_user



  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def create
   @user = User.new(user_params)
   @user.user_id = current_user.id
   @user.save
   redirect_to book_path(@book.id)
  end

  def show
    # Parameters: {"id"=>"3"}
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    # Book.find(params[:id])
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follow
    @following_users = current_user.following_user
  end

  def follower
    @follower_users = current_user.follower_user
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, format:'jpeg', size: "50x50", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followers.count %></td>
        <td>フォロワー数：<%= user.follow.count %></td>
        <td><% if current_user != user %>
              <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :DELETE %>
              <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
              <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, format:'jpeg', size: "100x100", fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>



  <tr>
    <th>follows <%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers <%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :DELETE, class: "btn btn-info" %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: 'btn btn-success' %>
    <% end %>
  <% end %>

<br>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/follow.html.erb
<table class = 'table'>
 <h1>Follow Users</h1>
  <thead>
   <tr>
     <th>images</th>
     <th>names</th>
   <tr>
     <% @following_users.each do |following_user| %>

    <td><%= attachment_image_tag(following_user, :profile_image, format:'jpeg', size: "50x50", fallback: "no-image-icon.jpg") %></td>
    <td><%= following_user.name %></td>
    <td><%= link_to 'フォロー外す', user_relationships_path(following_user.id), method: :delete %></td>
  </tr>
 <% end %>
 </thead>
</table>

app/views/users/follower.html.erb
<table class = 'table'>
   <h1>Follower Users</h1>
    <thead>
        <tr>
          <th>image</th>
          <th>name</th>
        </tr>
    </thead>
    <tbody>
        <% @follower_users.each do |follower_user| %>
        <tr>
          <td><%= attachment_image_tag(follower_user, :profile_image, format:'jpeg', size: "50x50", fallback: "no-image-icon.jpg") %></td>
          <td><%= follower_user.name %></td>
          <td>ユーザー数：<%= follower_user.follower.count %></td>
          <td>フォロワー数：<%= follower_user.followed.count %></td>
          <td><%= link_to "show", user_path(follower_user) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User information</h2>
      <%= render 'info', user: @user %>
      <br>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books, book_favorite: @book_favorite %>
    </div>
  </div>
</div>