config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get 'search' => 'searches#search'

  resources :users, only: [:create, :show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]

    if @range == '1'
      @user = User.search(search, word)
    else
      @book = Book.search(search, word)
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<table class='table table-hover table-inverse'>
  <% if @range =='2' %>
   <h1>Book search for "<%= :word %>"</h1>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
        <th></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @book.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag(book.user, :profile_image, format:'jpeg', size: "50x50", fallback: "no-image-icon.jpg") %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>

 <% else %>
   <thead>
     <h1>User search for "<%= :word %>"</h1>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, format:'jpeg', size: "50x50", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followers.count %></td>
        <td>フォロワー数：<%= user.followings.count %></td>
        <td><% if current_user != user %>
              <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :DELETE %>
              <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
              <% end %>
            <% end %>
        </td>
    <% end %>
  </tbody>
<% end %>
</table>